<?php
$forecast = $this->getWeatherData();
$rawData = unserialize($forecast['rawData']);
$parsedData = $this->getParsedData($rawData);
$windDirection = $this->getWindDirection($rawData);
?>

<div class="block footer-weather">
    <div class="block-title" style="margin: 0 auto;width: 250px">
        <strong>
            <span>
                The weather in
                <?php echo $forecast["location"] ?>
            </span>
        </strong>
    </div>
    <ul style="list-style-type: disc;-webkit-columns: 2;-moz-columns: 2;columns: 2;list-style-position: inside;">
        <?php foreach ($parsedData as $label => $value): ?>
            <li>
                <?php
                    echo $label . $value;
                    if ($label == 'Wind: ') {
                        echo $windDirection;
                    }
                ?>
            </li>
        <?php endforeach ?>
    </ul>
    <img src="<?php echo $forecast["iconUrl"] ?>"
         width="75"
         height="45"
         alt="<?php echo $parsedData['General conditions: '] ?>"
         title="<?php echo $parsedData['General conditions: '] ?>"
    >
</div>
